services:
  app:
    image: scrm:latest
    container_name: scrm-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - scrm_data:/data

volumes:
  scrm_data:
    external: true
    name: scrm-backup_scrm_data
