server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # 指向我们在 docker-compose 里挂载进来的目录
    root   /usr/share/nginx/html;

    # 开启目录浏览（核心所在：没有 index.html 也能列出所有文件）
    autoindex on;
    autoindex_exact_size off; 
    autoindex_localtime on;   

    # 强制指定字符编码，彻底消灭乱码
    charset utf-8;

    location / {
        # 补充 MIME 类型，防止 .md 等文本文件被强行下载
        types {
            text/markdown md; # 把 text/plain 改成 text/markdown
            text/plain txt;
        }
        default_type text/plain;
        
        # 优先尝试访问具体的 URI，找不到再去尝试 index.html
        try_files $uri $uri/ /index.html;
    }

    # 遇到 50x 错误时，优雅地展示 50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}